language: node_js
node_js:
  - stable
branches:
  - master
cache:
  directories:
    - node_modules
before_install:
  - cd ./server
addons:
  sonarcloud:
    organization: meck93
    token:
      secure: klmraWYReUOnS5jy6SLsy2XMeNsFswbvFYkj2F/Ba53sYI1y8SOlzwY3nZiAt1sSkmYmgpNpnCcrfVTp4TLp0SDkihJzhZsZi+1ytEihdC+vRJEln4FXuSbo1Fi/9W7qXKklBb4NRQnb+TJ39mynxxUjyOrSbFHpiz+PMMzY2dFU6AxX26UzGXw16AebNcaBdpCkdNoIkzmnv8LZ4HZ6L7A5UcpmIT8+SA1n2HBqqeLigVR3i4s9oYH4gq3rEi2VbQ95eQV/ztRlMflnmIah4eFQCXLnyzb7VDLcnu+JZUBakzhNnUeT1Ryp5hZpAf1eKcFJoDerVDfxkLiL/EFcf59DQO6hXP449SAD8I9ks8J/iWyy657QeOYuwIKx1RFcVCX2YIxDq1cTJlb9Szlie266SrBy+fQAILfsrR06S8bOQ4NeRg9glaXlVPSV5eckFLrQcvm/HjypIhkA7m7jiyksyF2lFjugq+it6Ac2Jf4dRzMES9TJyRotYrdv4TxEM2IpwYER2bqYAOV6GPfqI8Yr4jivuoCiPGa4fW3frR+Acv8DtUQfpJG4jEc4SozZ/kzf9SPJ74EV0IAyvByX13ngIjbXR7OTWaDqpRrB2hcUojWCnrtYt96F33PKwRn5sb2Qcxs+yQJGdN3y8cxxd91p6F27YRSP9WKAwJdB/tE=
install:
  - npm install
script:
  - npm run build
  - npm run test
  - sonar-scanner -X -D sonar.projectKey=meck93_ScanOrUploadMe
deploy:
  provider: heroku
  api_key:
    secure: D76cBDHO39fsikyMQEeT9auxijHGKWDVLSHAG0h7HWvkmO6G2GqZSY+aBetGDwBaG7XbCJkOpZXOdfEpM/HXN68K7XR+zt8XmcRCk7ZaN0jyfREva8AotOOpZHqFr3o8yol4Vaje+rqEz/Q+Zmnl5YHbm568LA+82sH7ndc2qcouYsUOcLqQZrcBqL6JmGM0NvmJtcr1g2KKXQcDfGFkUnvdA8ZeRJxzkW8LUD2U+sJiy2AqdkU1MZ/XCM58oQCBIItpQlqbOZlsXIx4yR9uObwJaIiNiFMQYvJ2HD7QG84q9I0Zs/GxaEd5V/U2YUAThiwaaYDAWiG0D2jMxG5Zx73tHJcld2HwAn+cOIj8Ja7PvGfVYgl+xp6pWGcVg3DoxQ+OlI1hbVqoI03gIxd3MVvwXqt90mA4Y5yPvgU8PYyh69JL2ylrm7bbJndYFNNCA084C1PNzD5JI6Nt/7vPJyfXR1x+CyDtmMxIcTtld2eLZXHPqC4eKAYs0RXVORUqZyh//w2+lVewnRTPEUWJ+FuRHUnfrVUPkDj4enV+bXKHwZQllo5kuuMxwTe0qFSOpuMpTlLYp7ApUZkY4P2XCo5btBQleDmK9mUNEDHJ5lN3FeyeVOcAfLIV9pjr/LGM0szukwmv28MjIoV3rRT8fAIsbSJlZuzmuaTCJNkMQnc=
  app: scanoruploadme
notifications:
  email: false
env:
  global:
    - secure: SONAR_TOKEN=klmraWYReUOnS5jy6SLsy2XMeNsFswbvFYkj2F/Ba53sYI1y8SOlzwY3nZiAt1sSkmYmgpNpnCcrfVTp4TLp0SDkihJzhZsZi+1ytEihdC+vRJEln4FXuSbo1Fi/9W7qXKklBb4NRQnb+TJ39mynxxUjyOrSbFHpiz+PMMzY2dFU6AxX26UzGXw16AebNcaBdpCkdNoIkzmnv8LZ4HZ6L7A5UcpmIT8+SA1n2HBqqeLigVR3i4s9oYH4gq3rEi2VbQ95eQV/ztRlMflnmIah4eFQCXLnyzb7VDLcnu+JZUBakzhNnUeT1Ryp5hZpAf1eKcFJoDerVDfxkLiL/EFcf59DQO6hXP449SAD8I9ks8J/iWyy657QeOYuwIKx1RFcVCX2YIxDq1cTJlb9Szlie266SrBy+fQAILfsrR06S8bOQ4NeRg9glaXlVPSV5eckFLrQcvm/HjypIhkA7m7jiyksyF2lFjugq+it6Ac2Jf4dRzMES9TJyRotYrdv4TxEM2IpwYER2bqYAOV6GPfqI8Yr4jivuoCiPGa4fW3frR+Acv8DtUQfpJG4jEc4SozZ/kzf9SPJ74EV0IAyvByX13ngIjbXR7OTWaDqpRrB2hcUojWCnrtYt96F33PKwRn5sb2Qcxs+yQJGdN3y8cxxd91p6F27YRSP9WKAwJdB/tE=
